#define TK_PACKAGE                         1
#define TK_PKGNAME                         2
#define TK_SEMI                            3
#define TK_IDENTIFIER                      4
#define TK_SUB                             5
#define TK_OPEN_CURLY                      6
#define TK_CLOSE_CURLY                     7
#define TK_DO                              8
#define TK_MY                              9
#define TK_SCALAR_VAR                     10
#define TK_HASH_VAR                       11
#define TK_ARRAY_VAR                      12
#define TK_INTEGER                        13
#define TK_DOUBLE                         14
#define TK_STRING                         15
#define TK_HASH                           16
#define TK_ARRAY                          17
#define TK_ANY                            18
#define TK_OBJECT                         19
#define TK_SPACE                           20
